package exceptionP;

public class Test {
    public static void main(String[] args) throws Exception {
//        System.out.println("第一段运行");
//        Integer i=1;
//        try{
//            System.out.println(i/0);
//        }catch (Exception e){
//            System.out.println("不能除0");
//            System.out.println(e.getMessage());
//        }
//        System.out.println("正常运行代码");



//        Integer j=11;
//        if(j>10){
//            throw new Exception("报错");
//        }

//        List<Integer> list=new ArrayList<>();
//        Integer i=0;
//        while(true){
//            i++;
//            list.add(i);
//            System.out.println(list.size());
//        }


//        try {
//            int[] a=new int[1024*1024];
//        }catch (Exception e){
//            System.out.println("栈溢出");
//        }

//        System.out.println("第一段运行");

//        Integer a[]={1,2,3};
//        System.out.println(a[3]);

//        Object o = new Object();
//        String s=(String) o;

    }
}
